# Generated by Django 5.2.6 on 2025-09-26 16:37

import autenticacao.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariopersonalizado',
            managers=[
                ('objects', autenticacao.models.UsuarioPersonalizadoManager()),
            ],
        ),
    ]
