name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  docs:
    name: mkdocs deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

    - name: Using cache to MkDocs
      uses: actions/cache@v3
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    - run: pip install mkdocs-material 

    - name: Build Docs
      run: mkdocs build --site-dir public

    - name: Deploy Docs to gh-pages-docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages-docs